### ISSUE TITLE
Local development improvement request

### ISSUE THREAD

**Issue by zygimantas** [verto-health/ngx-turnstile#33]
Would it be possible to have enabled (boolean) property?

Use case:

When developing on localhost, it would be good option to set [enabled]="environment.production" disable functionality of widget. Otherwise, it must be used like this:

```
@if (environment.production) {
  <ngx-turnstile [(ngModel)]="token" />
}
```
which makes `form.value.token` undefined in template driven form.

Suggested solution:
```
<ngx-turnstile [(ngModel)]="token" [enabled]="environment.production" />
```

**Comment by choyiny** [comment]
So far, we have not encountered a situation where it should be disabled in development mode. Since our backend always have the validation code, we opted in to put in test keys on both frontend and backend so the validation always succeeds: https://developers.cloudflare.com/turnstile/troubleshooting/testing/

Does this work for your use case? If not, can you tell me more about why you need to disable the widget in development mode?

**Comment by zygimantas** [comment]
Yes, that would work in my case. Thank you.
